run:
  timeout: 5m
  issues-exit-code: 1

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
