{{- if .Values.secrets.tsdbToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry-collector.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  tsdb-token: {{ .Values.secrets.tsdbToken | b64enc | quote }}
{{- end }}
