apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telemetry-api.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  service_name: {{ .service.name | quote }}
  service_port: {{ .service.port | quote }}
  log_level: {{ .service.logLevel | quote }}
  tsdb_url: {{ .tsdb.url | quote }}
  tsdb_org: {{ .tsdb.org | quote }}
  tsdb_bucket: {{ .tsdb.bucket | quote }}
  tsdb_retry_attempts: {{ .tsdb.retryAttempts | quote }}
  tsdb_query_timeout: {{ .tsdb.queryTimeout | quote }}
  {{- end }}
