apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telemetry-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "telemetry-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "telemetry-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "telemetry-api.serviceAccountName" . }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- with .Values.tsdb }}
        - name: TSDB_URL
          value: {{ .url | quote }}
        - name: TSDB_ORG
          value: {{ .org | quote }}
        - name: TSDB_BUCKET
          value: {{ .bucket | quote }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.secrets.tsdbToken }}
        - name: TSDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "telemetry-api.fullname" . }}-secret
              key: tsdb-token
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 12 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
