apiVersion: v2
name: messagebroker
description: A Kafka-like distributed message queue system
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - messagebroker
  - kafka
  - distributed
  - queue
maintainers:
  - name: MessageBroker Team
    email: team@messagebroker.io
home: https://github.com/dhruvit2/messagebroker
sources:
  - https://github.com/dhruvit2/messagebroker
